// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfb9-kIZ-yByZgBpD72A1wh1gmKrcGMws',
    appId: '1:1037537309592:web:2cc61d165409a4055331ed',
    messagingSenderId: '1037537309592',
    projectId: 'cloud-storage-3bad6',
    authDomain: 'cloud-storage-3bad6.firebaseapp.com',
    storageBucket: 'cloud-storage-3bad6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4WRhVKBRD78qp8p-VEcXG1kkJD7gkrf8',
    appId: '1:1037537309592:android:9b516258d390bd8f5331ed',
    messagingSenderId: '1037537309592',
    projectId: 'cloud-storage-3bad6',
    storageBucket: 'cloud-storage-3bad6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdahSHza8PS-uhrCDybclOrCRK60YfmfU',
    appId: '1:1037537309592:ios:0de664efbd1b82965331ed',
    messagingSenderId: '1037537309592',
    projectId: 'cloud-storage-3bad6',
    storageBucket: 'cloud-storage-3bad6.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseCloudMessaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdahSHza8PS-uhrCDybclOrCRK60YfmfU',
    appId: '1:1037537309592:ios:0de664efbd1b82965331ed',
    messagingSenderId: '1037537309592',
    projectId: 'cloud-storage-3bad6',
    storageBucket: 'cloud-storage-3bad6.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseCloudMessaging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfb9-kIZ-yByZgBpD72A1wh1gmKrcGMws',
    appId: '1:1037537309592:web:362b8134ec849b825331ed',
    messagingSenderId: '1037537309592',
    projectId: 'cloud-storage-3bad6',
    authDomain: 'cloud-storage-3bad6.firebaseapp.com',
    storageBucket: 'cloud-storage-3bad6.firebasestorage.app',
    measurementId: 'G-STL74Y4LDQ',
  );
}
