// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD3MQe0RKWhlB3OGVTtXHJzk7F1cLdw0k',
    appId: '1:847482387989:web:bf0bf413ab57606e5fd81c',
    messagingSenderId: '847482387989',
    projectId: 'gallery-app-dam',
    authDomain: 'gallery-app-dam.firebaseapp.com',
    storageBucket: 'gallery-app-dam.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh8Dhm09GYsOBfLNfJrx7y-m8hq4Oxuac',
    appId: '1:847482387989:android:f9fc88da99e2c4405fd81c',
    messagingSenderId: '847482387989',
    projectId: 'gallery-app-dam',
    storageBucket: 'gallery-app-dam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9PV7MFqDrrrNaN-gNvqXZy96asM4mt-I',
    appId: '1:847482387989:ios:21d644efacede6895fd81c',
    messagingSenderId: '847482387989',
    projectId: 'gallery-app-dam',
    storageBucket: 'gallery-app-dam.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9PV7MFqDrrrNaN-gNvqXZy96asM4mt-I',
    appId: '1:847482387989:ios:21d644efacede6895fd81c',
    messagingSenderId: '847482387989',
    projectId: 'gallery-app-dam',
    storageBucket: 'gallery-app-dam.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD3MQe0RKWhlB3OGVTtXHJzk7F1cLdw0k',
    appId: '1:847482387989:web:5ac089db8f5870065fd81c',
    messagingSenderId: '847482387989',
    projectId: 'gallery-app-dam',
    authDomain: 'gallery-app-dam.firebaseapp.com',
    storageBucket: 'gallery-app-dam.firebasestorage.app',
  );
}
